name: PIPELINE

on:
  push:
    branches:
      - develop
      - release
      - main

  pull_request:
    branches:
      - develop
      - release
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Check Node version
        run: node --version

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration production 

      - name: Upload Artifact (Dist)
        uses: actions/upload-artifact@v4
        with:
          name: planeja-financeiro-app-frontEnd
          path: dist/Planeja-app